#!/usr/bin/env python
#
# Copyright 2010 Markus Pielmeier
#
# This file is part of tagfs utils.
#
# tagfs utils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tagfs utils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tagfs utils.  If not, see <http://www.gnu.org/licenses/>.
#

import optparse
import os
import logging
import sys
from tag_utils import tag_io
from tag_utils import decision_tree as dt
from tag_utils import log_config

def askQuestion(q):
    items = list(q.items)
    itemsCount = len(items)
    print 'Still %s possible items' % itemsCount

    if itemsCount < 5:
        for i in items:
            print ' * %s' % i.fileName

    print q.questionText

    possibleAnswers = q.answers
    print ', '.join(['[' + str(i) + '] ' + possibleAnswers[i] for i in range(len(possibleAnswers))])

    input = sys.stdin.readline()
    
    answers = []
    for s in input.split():
        answers.append(possibleAnswers[int(s)])

    q.answer(answers)

def main():
    usage = 'usage: %prog [item directory]'
    parser = optparse.OptionParser()
    
    (options, args) = parser.parse_args()

    if len(args) == 0:
        parser.print_help()

        return 1

    itemDirectory = args[0]

    db = tag_io.parseDatabaseDirectory(itemDirectory)

    q = dt.findItem(db)
    lq = q

    while q != None:
        askQuestion(q)

        lq = q

        q = q.nextQuestion

    print 'Resulting items are:'
    for i in lq.items:
        print ' * %s' % i.fileName

    return 0

if __name__ == '__main__':
    log_config.setUpLogging()

    sys.exit(main())
