#!/usr/bin/env python
#
# Copyright 2010 Markus Pielmeier
#
# This file is part of tagfs utils.
#
# tagfs utils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tagfs utils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tagfs utils.  If not, see <http://www.gnu.org/licenses/>.
#

import optparse
from tag_utils import dom

class AppendCommand(object):

    def __init__(self):
        self.cmd = 'add'

    def execute(self, item, args):
        tagging = args[0]


        return 1

class SetCommand(object):

    def __init__(self):
        self.cmd = 'set';

    def execute(self, item, args):
        tagging = args[0]


        return 1

COMMANDS = {}

def addCommand(c):
    COMMANDS[c.cmd] = c

addCommand(AppendCommand())
addCommand(SetCommand())

def main():
    parser = optparse.OptionParser()
    
    (options, args) = parser.parse_args()

    target = args[0]
    commands = args[1:]

    item = # TODO parse Item

    i = 0
    while i < len(commands):
        cmd = commands[i]
        
        c = COMMANDS[cmd]

        i = i + c.execute(item, commands[i:])

    # TODO
    pass

if __name__ == '__main__':
    main()
